# Generated by Django 4.1.3 on 2022-12-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_alter_movie_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='salary',
            field=models.IntegerField(blank=True, default=1000000),
        ),
    ]
