# Generated by Django 4.1.3 on 2022-12-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_alter_movie_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='salary',
            field=models.IntegerField(blank=True, default=1000000, null=True),
        ),
    ]
