# Generated by Django 4.1.3 on 2022-12-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0009_movie_director_alter_movie_rating_alter_movie_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director_email',
            field=models.EmailField(default='pussy_destroir@mail.ru', max_length=254),
        ),
    ]
